/* // lib/mockData.ts

import { JobListing } from "../types/job";


export const jobData: JobListing[] = [
  {
    id: '1',
    title: 'Frontend Developer',
    department: 'Engineering',
    location: 'Remote',
    type: 'Full-time',
    experience: '3+ years',
    salary: '₹80,000 - ₹100,000',
    postedDate: new Date('2024-06-01'),
    description: 'Build user-facing features with React.',
    requirements: ['3+ years React', 'HTML/CSS', 'REST APIs'],
    responsibilities: ['Develop UI', 'Collaborate with design', 'Write tests'],
    benefits: ['Health insurance', 'Remote work', 'Flexible hours']
  },
  {
    id: '2',
    title: 'Backend Developer',
    department: 'Engineering',
    location: 'Hyderabad',
    type: 'Contract',
    experience: '5+ years',
    salary: '₹60/hr',
    postedDate: new Date('2024-06-10'),
    description: 'Build scalable backend services with Node.js.',
    requirements: ['Node.js', 'MongoDB', 'REST & GraphQL'],
    responsibilities: ['Write APIs', 'Integrate DBs', 'Handle auth'],
    benefits: ['Contract flexibility', 'Tech events']
  },
  {
    id: '3',
    title: 'UI/UX Designer',
    department: 'Design',
    location: 'Bangalore',
    type: 'Full-time',
    experience: '2+ years',
    salary: '₹60,000 - ₹80,000',
    postedDate: new Date('2024-06-12'),
    description: 'Design intuitive user interfaces and experiences.',
    requirements: ['Figma', 'User Research', 'Prototyping'],
    responsibilities: ['Create wireframes', 'Design UI', 'Test usability'],
    benefits: ['Health insurance', 'Design workshops']
  },
  {
    id: '4',
    title: 'Data Scientist',
    department: 'Data Science',
    location: 'Remote',
    type: 'Full-time',
    experience: '4+ years',
    salary: '₹120,000',
    postedDate: new Date('2024-05-28'),
    description: 'Work on machine learning and data analysis.',
    requirements: ['Python', 'TensorFlow', 'Data Visualization'],
    responsibilities: ['Analyze data', 'Build models', 'Interpret insights'],
    benefits: ['Stock options', 'Health insurance']
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    department: 'Engineering',
    location: 'Chennai',
    type: 'Full-time',
    experience: '3+ years',
    salary: '₹90,000',
    postedDate: new Date('2024-06-15'),
    description: 'Manage CI/CD pipelines and cloud infrastructure.',
    requirements: ['AWS', 'Docker', 'CI/CD'],
    responsibilities: ['Deploy services', 'Monitor systems', 'Automate infra'],
    benefits: ['Learning stipend', 'Remote option']
  },
  {
    id: '6',
    title: 'Product Manager',
    department: 'Product',
    location: 'Mumbai',
    type: 'Full-time',
    experience: '5+ years',
    salary: '₹150,000',
    postedDate: new Date('2024-06-02'),
    description: 'Lead product lifecycle from planning to execution.',
    requirements: ['Agile', 'Product Roadmaps', 'Stakeholder Management'],
    responsibilities: ['Define product vision', 'Coordinate teams', 'Launch features'],
    benefits: ['Leadership training', 'Performance bonuses']
  },
  {
    id: '7',
    title: 'QA Engineer',
    department: 'Quality Assurance',
    location: 'Remote',
    type: 'Internship',
    experience: '0-1 year',
    postedDate: new Date('2024-05-20'),
    description: 'Assist in software quality assurance and testing.',
    requirements: ['Basic testing knowledge', 'Attention to detail'],
    responsibilities: ['Run test cases', 'Log bugs', 'Support devs'],
    benefits: ['Internship certificate', 'Learning opportunity']
  },
  {
    id: '8',
    title: 'Mobile App Developer',
    department: 'Engineering',
    location: 'Delhi',
    type: 'Full-time',
    experience: '2+ years',
    salary: '₹70,000 - ₹90,000',
    postedDate: new Date('2024-06-05'),
    description: 'Develop mobile apps for iOS and Android.',
    requirements: ['Flutter', 'React Native', 'UI Development'],
    responsibilities: ['Build apps', 'Fix bugs', 'Push updates'],
    benefits: ['Flexible hours', 'Annual app summit']
  },
  {
    id: '9',
    title: 'HR Executive',
    department: 'HR',
    location: 'Pune',
    type: 'Full-time',
    experience: '2+ years',
    salary: '₹50,000 - ₹60,000',
    postedDate: new Date('2024-06-18'),
    description: 'Handle recruitment, onboarding, and employee engagement.',
    requirements: ['HRMS tools', 'Interviewing skills', 'Employee relations'],
    responsibilities: ['Recruit staff', 'Organize training', 'Maintain records'],
    benefits: ['HR certification support', 'Work from home option']
  },
  {
    id: '10',
    title: 'Marketing Specialist',
    department: 'Marketing',
    location: 'Kolkata',
    type: 'Part-time',
    experience: '1+ year',
    salary: '₹30,000 - ₹50,000',
    postedDate: new Date('2024-06-20'),
    description: 'Execute digital marketing campaigns.',
    requirements: ['SEO', 'Social Media', 'Google Ads'],
    responsibilities: ['Create posts', 'Track metrics', 'Optimize campaigns'],
    benefits: ['Performance bonus', 'Remote work']
  },
  {
    id: '11',
    title: 'Technical Support Engineer',
    department: 'Support',
    location: 'Ahmedabad',
    type: 'Full-time',
    experience: '2+ years',
    salary: '₹40,000 - ₹55,000',
    postedDate: new Date('2024-06-01'),
    description: 'Provide technical assistance to customers.',
    requirements: ['Troubleshooting', 'Customer support', 'Basic networking'],
    responsibilities: ['Answer tickets', 'Resolve issues', 'Escalate when needed'],
    benefits: ['Night shift allowance', 'On-job training']
  },
  {
    id: '12',
    title: 'Graphic Designer',
    department: 'Design',
    location: 'Hyderabad',
    type: 'Contract',
    experience: '3+ years',
    salary: '₹40,000',
    postedDate: new Date('2024-06-03'),
    description: 'Design branding materials and assets.',
    requirements: ['Adobe Suite', 'Creativity', 'Typography'],
    responsibilities: ['Design brochures', 'Create assets', 'Revise feedback'],
    benefits: ['Creative freedom', 'Remote collaboration']
  },
  {
    id: '13',
    title: 'AI Engineer',
    department: 'Engineering',
    location: 'Remote',
    type: 'Full-time',
    experience: '4+ years',
    salary: '₹130,000',
    postedDate: new Date('2024-06-12'),
    description: 'Develop AI-based features using ML and DL.',
    requirements: ['Python', 'Pandas', 'Transformer Models'],
    responsibilities: ['Build models', 'Train datasets', 'Optimize output'],
    benefits: ['GPU access', 'Research publication support']
  },
  {
    id: '14',
    title: 'Security Analyst',
    department: 'IT Security',
    location: 'Noida',
    type: 'Full-time',
    experience: '3+ years',
    salary: '₹100,000',
    postedDate: new Date('2024-06-08'),
    description: 'Ensure cybersecurity and monitor threats.',
    requirements: ['SIEM', 'Firewalls', 'Ethical Hacking'],
    responsibilities: ['Monitor systems', 'Run scans', 'Report incidents'],
    benefits: ['Security certifications', 'Work-from-anywhere']
  },
  {
    id: '15',
    title: 'Sales Manager',
    department: 'Sales',
    location: 'Mumbai',
    type: 'Full-time',
    experience: '5+ years',
    salary: '₹90,000 + commission',
    postedDate: new Date('2024-05-25'),
    description: 'Lead B2B sales initiatives and close deals.',
    requirements: ['CRM tools', 'Lead Generation', 'Negotiation'],
    responsibilities: ['Generate leads', 'Meet clients', 'Achieve targets'],
    benefits: ['High incentives', 'Company car']
  },
  {
    id: '16',
    title: 'Content Writer',
    department: 'Content',
    location: 'Remote',
    type: 'Part-time',
    experience: '2+ years',
    salary: '₹25,000 - ₹40,000',
    postedDate: new Date('2024-06-01'),
    description: 'Write engaging blogs and marketing content.',
    requirements: ['SEO Writing', 'Grammarly', 'WordPress'],
    responsibilities: ['Write articles', 'Edit drafts', 'Research topics'],
    benefits: ['Remote forever', 'Content writing workshops']
  },
  {
    id: '17',
    title: 'Legal Advisor',
    department: 'Legal',
    location: 'Delhi',
    type: 'Contract',
    experience: '6+ years',
    salary: '₹120,000',
    postedDate: new Date('2024-06-04'),
    description: 'Handle legal compliance and corporate law.',
    requirements: ['LLB', 'Corporate Law', 'Compliance'],
    responsibilities: ['Review contracts', 'Advise stakeholders', 'Stay compliant'],
    benefits: ['Work flexibility', 'Legal resource access']
  },
  {
    id: '18',
    title: 'Office Assistant',
    department: 'Admin',
    location: 'Chennai',
    type: 'Full-time',
    experience: '1+ year',
    salary: '₹20,000',
    postedDate: new Date('2024-06-10'),
    description: 'Handle clerical tasks and office errands.',
    requirements: ['MS Office', 'Communication', 'Time Management'],
    responsibilities: ['Manage files', 'Assist staff', 'Support logistics'],
    benefits: ['Paid holidays', 'Meal coupons']
  },
  {
    id: '19',
    title: 'Business Analyst',
    department: 'Business',
    location: 'Pune',
    type: 'Full-time',
    experience: '3+ years',
    salary: '₹85,000',
    postedDate: new Date('2024-06-14'),
    description: 'Analyze business needs and propose solutions.',
    requirements: ['Data Analysis', 'Reporting Tools', 'Agile'],
    responsibilities: ['Gather requirements', 'Report insights', 'Collaborate with PMs'],
    benefits: ['Skill training', 'Certification support']
  },
  {
    id: '20',
    title: 'Recruiter',
    department: 'HR',
    location: 'Remote',
    type: 'Contract',
    experience: '2+ years',
    salary: '₹50,000 + incentive',
    postedDate: new Date('2024-06-09'),
    description: 'Source and screen candidates for various roles.',
    requirements: ['Recruitment Tools', 'Communication', 'LinkedIn Sourcing'],
    responsibilities: ['Post jobs', 'Conduct interviews', 'Manage database'],
    benefits: ['Incentives', 'Remote forever']
  }


];
 */